### ISSUE TITLE
linear probing code details

### ISSUE THREAD

**Issue by VaeReol** [cheliu-computation/MERL-ICML2024#1]
Hello,

Thank you very much for sharing your outstanding work. I am a beginner in deep learning, and I wonder if you could provide the specific code for the downstream task, particularly the linear probing part. I have followed the current parameters, but there is a discrepancy between my results and the data presented in the paper. If you could share the new code, I would be very grateful.

Thank you.

**Comment by cheliu-computation** [comment]
Thanks for your interest on our work!
For the linear probing details, please refer to the folder 'finetune', it has all data split and the script for the linear probing.

**Comment by VaeReol** [comment]
i get it, thank you so much.
