### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by VaeReol** [cheliu-computation/MERL-ICML2024#2]
May I ask if the pre-training parameters are as follows？

optimizer:
  params:
    lr: 2.0e-4
    weight_decay: 1.0e-5

max_epochs: 50
batch_size: 512
network:
  ecg_model: resnet18
  num_leads: 12
  ### this part does not control builder/trainer
  text_model: ncbi/MedCPT-Query-Encoder
  free_layers: 6 # set 12 to freeze all layer in bert
  feature_dim: 768

  projection_head:
    mlp_hidden_size: 256
    projection_size: 256

**Comment by cheliu-computation** [comment]
Hi, thanks for your interest on our work!

Please refer to https://github.com/cheliu-computation/MERL-ICML2024/blob/main/pretrain/config.yaml for pretraining setting, and the scripts should read the config automatically.
