### ISSUE TITLE
dimensions do not match when loading

### ISSUE THREAD

**Issue by zhouxw12345** [cheliu-computation/MERL-ICML2024#6]
Thank you for your outstanding work. Recently, I have been studying your paper, but I have encountered some issues and look forward to your guidance.
In the code provided, in the `main_single.py` file:  
```python
model.load_state_dict(ckpt, strict=False)
print(f'load pretrained model from {args.pretrain_path}, the backbone is {args.backbone}, using {args.num_leads} leads')
if 'linear' in args.name:
    for param in model.parameters():
        param.requires_grad = False
    print(f'freeze backbone for {args.name} with {args.backbone}')
        
for param in model.linear.parameters():
    param.requires_grad = True  
```

This section already makes adjustments for loading the model, but when I run the file `finetune/sub_script/chapman/sub_chapman.sh`, I encounter the following error:  
```plaintext
Traceback (most recent call last):
  File "/home/zhouxw/model/MERL/finetune/main_single.py", line 371, in <module>
    main()
  File "/home/zhouxw/model/MERL/finetune/main_single.py", line 155, in main
    model.load_state_dict(ckpt, strict=False)
  File "/usr/local/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNet:
        size mismatch for linear.weight: copying a param with shape torch.Size([10, 512]) from checkpoint, the shape in current model is torch.Size([38, 512]).
        size mismatch for linear.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([38]).
```

Should the model be adjusted in this section? Thank you for your assistance!

**Comment by FELIN0366** [comment]
Thank you for your excellent work. Recently, I have download and prepared to dulplicate your code. Due to the cache limitation, I only select 1000 ecg data to process and also modify distributed code to single gpu code. Howerver, the result is too bad to run the validation set. Does someone run the full code and it's pleasure for you to give me some advise.
![01](https://github.com/user-attachments/assets/ca222db8-60f6-41f9-b5f1-fe00b6cf0fdf)
![02](https://github.com/user-attachments/assets/4a12555a-0883-43ba-a638-a33cea983809)

**Comment by cheliu-epsilon** [comment]
> Thank you for your excellent work. Recently, I have download and prepared to dulplicate your code. Due to the cache limitation, I only select 1000 ecg data to process and also modify distributed code to single gpu code. Howerver, the result is too bad to run the validation set. Does someone run the full code and it's pleasure for you to give me some advise. ![01](https://private-user-images.githubusercontent.com/88762268/398349580-ca222db8-60f6-41f9-b5f1-fe00b6cf0fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjg4OTksIm5iZiI6MTczNTAyODU5OSwicGF0aCI6Ii84ODc2MjI2OC8zOTgzNDk1ODAtY2EyMjJkYjgtNjBmNi00MWY5LWI1ZjEtZmUwMGI2Y2YwZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YzVlODg1MjE2MDA5ZDc4OTkxY2Q3ZTJhNDgyMjVkMmYyNmU3MTA3ZTlhMjJmM2FkOWIzYzQwMDUwZDExY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LUgstC5J-WcxgK0CT56WjiWUHhwiQ70oW3TkEzVCh6Q) ![02](https://private-user-images.githubusercontent.com/88762268/398349595-4a12555a-0883-43ba-a638-a33cea983809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjg4OTksIm5iZiI6MTczNTAyODU5OSwicGF0aCI6Ii84ODc2MjI2OC8zOTgzNDk1OTUtNGExMjU1NWEtMDg4My00M2JhLWE2MzgtYTMzY2VhOTgzODA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4M2I1YzkxODdkNmMyOGZhYWE2Nzg3ODgxNGZiNmEyZTE2YTBlYzliOGI5YTVmZDdlMDExZjJjZjQ2ZTVhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i-vntnl-gN9DXZanIivLHdXL5T2d0SPEXUjNp9QKZQU)

Thanks for your interest on our work.
First, our model pretrained on 800k ecg with 8 gpus. Normally CLIP-based pretraining rely on large-scale data. You mentioned only 1000 data, that is not suitable for CLIP-based pretraining.

**Comment by cheliu-computation** [comment]
> as your error message, chapman has 38 classes, but the model classifier weight is 10 dim.
> So, from pretrained ckpt, it should not include any weight about the linear layer, since we only used the encoder weight for downstream linear probing.

as your error message, chapman has 38 classes, but the model classifier weight is 10 dim.
So, from pretrained ckpt, it should not include any weight about the linear layer, since we only used the encoder weight for downstream linear probing.

**Comment by cheliu-computation** [comment]
> Thank you for your outstanding work. Recently, I have been studying your paper, but I have encountered some issues and look forward to your guidance. In the code provided, in the `main_single.py` file:
> 
> ```python
> model.load_state_dict(ckpt, strict=False)
> print(f'load pretrained model from {args.pretrain_path}, the backbone is {args.backbone}, using {args.num_leads} leads')
> if 'linear' in args.name:
>     for param in model.parameters():
>         param.requires_grad = False
>     print(f'freeze backbone for {args.name} with {args.backbone}')
>         
> for param in model.linear.parameters():
>     param.requires_grad = True  
> ```
> 
> This section already makes adjustments for loading the model, but when I run the file `finetune/sub_script/chapman/sub_chapman.sh`, I encounter the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/zhouxw/model/MERL/finetune/main_single.py", line 371, in <module>
>     main()
>   File "/home/zhouxw/model/MERL/finetune/main_single.py", line 155, in main
>     model.load_state_dict(ckpt, strict=False)
>   File "/usr/local/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for ResNet:
>         size mismatch for linear.weight: copying a param with shape torch.Size([10, 512]) from checkpoint, the shape in current model is torch.Size([38, 512]).
>         size mismatch for linear.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([38]).
> ```
> 
> Should the model be adjusted in this section? Thank you for your assistance!

as your error message, chapman has 38 classes, but the model classifier weight is 10 dim.
So, from pretrained ckpt, it should not include any weight about the linear layer, since we only used the encoder weight for downstream linear probing.

**Comment by cheliu-computation** [comment]
> Thank you for your excellent work. Recently, I have download and prepared to dulplicate your code. Due to the cache limitation, I only select 1000 ecg data to process and also modify distributed code to single gpu code. Howerver, the result is too bad to run the validation set. Does someone run the full code and it's pleasure for you to give me some advise. ![01](https://private-user-images.githubusercontent.com/88762268/398349580-ca222db8-60f6-41f9-b5f1-fe00b6cf0fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjkyMzYsIm5iZiI6MTczNTAyODkzNiwicGF0aCI6Ii84ODc2MjI2OC8zOTgzNDk1ODAtY2EyMjJkYjgtNjBmNi00MWY5LWI1ZjEtZmUwMGI2Y2YwZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMTk3NjBmMDNjMjhjNDU1MjFmNjY3YjE1MzA2ZDMzMzJkZTM0ZTQwNjRhN2I4YWJiZTg5M2ZmMDk0MjIxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C9FcI24y0V6pBtZNywhtrR35adA9bv-1rtu5h0M9at4) ![02](https://private-user-images.githubusercontent.com/88762268/398349595-4a12555a-0883-43ba-a638-a33cea983809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjkyMzYsIm5iZiI6MTczNTAyODkzNiwicGF0aCI6Ii84ODc2MjI2OC8zOTgzNDk1OTUtNGExMjU1NWEtMDg4My00M2JhLWE2MzgtYTMzY2VhOTgzODA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZjEyZWNlZGI2ZmMzMDhjZWFjNjJkYTllNTk5NDU5ZmVkNWJjZDdkOWE3MTQ0OTExNGUyMWY5MjBkZTYyOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yb4iRiLztqLCJ4DykYtxoSZ31QcXytPwy7DIZHuYOb0)

Thanks for your interest on our work.
First, our model pretrained on 800k ecg with 8 gpus. Normally CLIP-based pretraining rely on large-scale data. You mentioned only 1000 data, that is not suitable for CLIP-based pretraining.

**Comment by cheliu-computation** [comment]
> Thank you for your outstanding work. Recently, I have been studying your paper, but I have encountered some issues and look forward to your guidance. In the code provided, in the `main_single.py` file:
> 
> ```python
> model.load_state_dict(ckpt, strict=False)
> print(f'load pretrained model from {args.pretrain_path}, the backbone is {args.backbone}, using {args.num_leads} leads')
> if 'linear' in args.name:
>     for param in model.parameters():
>         param.requires_grad = False
>     print(f'freeze backbone for {args.name} with {args.backbone}')
>         
> for param in model.linear.parameters():
>     param.requires_grad = True  
> ```
> 
> This section already makes adjustments for loading the model, but when I run the file `finetune/sub_script/chapman/sub_chapman.sh`, I encounter the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/zhouxw/model/MERL/finetune/main_single.py", line 371, in <module>
>     main()
>   File "/home/zhouxw/model/MERL/finetune/main_single.py", line 155, in main
>     model.load_state_dict(ckpt, strict=False)
>   File "/usr/local/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for ResNet:
>         size mismatch for linear.weight: copying a param with shape torch.Size([10, 512]) from checkpoint, the shape in current model is torch.Size([38, 512]).
>         size mismatch for linear.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([38]).
> ```
> 
> Should the model be adjusted in this section? Thank you for your assistance!

as your error message, chapman has 38 classes, but the model classifier weight is 10 dim.
So, from pretrained ckpt, it should not include any weight about the linear layer, since we only used the encoder weight for downstream linear probing.

**Comment by FELIN0366** [comment]
> > Thank you for your excellent work. Recently, I have download and prepared to dulplicate your code. Due to the cache limitation, I only select 1000 ecg data to process and also modify distributed code to single gpu code. Howerver, the result is too bad to run the validation set. Does someone run the full code and it's pleasure for you to give me some advise. ![01](https://private-user-images.githubusercontent.com/88762268/398349580-ca222db8-60f6-41f9-b5f1-fe00b6cf0fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjkyMzYsIm5iZiI6MTczNTAyODkzNiwicGF0aCI6Ii84ODc2MjI2OC8zOTgzNDk1ODAtY2EyMjJkYjgtNjBmNi00MWY5LWI1ZjEtZmUwMGI2Y2YwZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMTk3NjBmMDNjMjhjNDU1MjFmNjY3YjE1MzA2ZDMzMzJkZTM0ZTQwNjRhN2I4YWJiZTg5M2ZmMDk0MjIxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C9FcI24y0V6pBtZNywhtrR35adA9bv-1rtu5h0M9at4) ![02](https://private-user-images.githubusercontent.com/88762268/398349595-4a12555a-0883-43ba-a638-a33cea983809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjkyMzYsIm5iZiI6MTczNTAyODkzNiwicGF0aCI6Ii84ODc2MjI2OC8zOTgzNDk1OTUtNGExMjU1NWEtMDg4My00M2JhLWE2MzgtYTMzY2VhOTgzODA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZjEyZWNlZGI2ZmMzMDhjZWFjNjJkYTllNTk5NDU5ZmVkNWJjZDdkOWE3MTQ0OTExNGUyMWY5MjBkZTYyOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yb4iRiLztqLCJ4DykYtxoSZ31QcXytPwy7DIZHuYOb0)
> 
> Thanks for your interest on our work. First, our model pretrained on 800k ecg with 8 gpus. Normally CLIP-based pretraining rely on large-scale data. You mentioned only 1000 data, that is not suitable for CLIP-based pretraining.

I’m very surprised that you were able to answer my question. I’d like to ask, how long did it take to run this model using 8 A100 GPUs? And is it possible to train this model in one GPU?
